changed function that checks for sort column
mintsoft/kodi.plugin.ytchannels pull request #14
Opened 2020-10-08 16:30 UTC by yeahme49

2020-10-10 07:34 UTC, mintsoft requested changes

2020-10-10 07:34 UTC, mintsoft commented on resources/lib/functions.py
> +#	cur = db.cursor()
Can you delete these comments?

2020-10-10 22:38 UTC, yeahme49 commented on resources/lib/functions.py
> +#	cur = db.cursor()
fixed

2020-10-11 15:57 UTC, merged

2020-10-11 15:57 UTC, mintsoft commented
Cool, thanks @yeahme49

2020-10-14 19:58 UTC, yeahme49 commented
i haven't seen the update hit the kodi repo, just wanted to make sure you were going to submit it

2020-10-15 20:24 UTC, mintsoft commented
@yeahme49 Yes, sorry. Been hectic, I'm packaging it up now

2020-10-15 20:50 UTC, mintsoft commented
https://github.com/xbmc/repo-plugins/pull/3167 and https://github.com/xbmc/repo-plugins/pull/3166